-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object.Book exposing (..)

import GraphQLBook.InputObject
import GraphQLBook.Interface
import GraphQLBook.Object
import GraphQLBook.Scalar
import GraphQLBook.ScalarCodecs
import GraphQLBook.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


author : SelectionSet String GraphQLBook.Object.Book
author =
    Object.selectionForField "String" "author" [] Decode.string


bookTranslations :
    SelectionSet decodesTo GraphQLBook.Object.TranslationBook
    -> SelectionSet (List decodesTo) GraphQLBook.Object.Book
bookTranslations object_ =
    Object.selectionForCompositeField "bookTranslations" [] object_ (identity >> Decode.list)


category :
    SelectionSet decodesTo GraphQLBook.Object.Category
    -> SelectionSet decodesTo GraphQLBook.Object.Book
category object_ =
    Object.selectionForCompositeField "category" [] object_ identity


id : SelectionSet GraphQLBook.ScalarCodecs.Id GraphQLBook.Object.Book
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder)


language :
    SelectionSet decodesTo GraphQLBook.Object.Language
    -> SelectionSet decodesTo GraphQLBook.Object.Book
language object_ =
    Object.selectionForCompositeField "language" [] object_ identity


numPages : SelectionSet Int GraphQLBook.Object.Book
numPages =
    Object.selectionForField "Int" "numPages" [] Decode.int


pages :
    SelectionSet decodesTo GraphQLBook.Object.Page
    -> SelectionSet (List decodesTo) GraphQLBook.Object.Book
pages object_ =
    Object.selectionForCompositeField "pages" [] object_ (identity >> Decode.list)


title : SelectionSet String GraphQLBook.Object.Book
title =
    Object.selectionForField "String" "title" [] Decode.string
