-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object.Page exposing (..)

import GraphQLBook.InputObject
import GraphQLBook.Interface
import GraphQLBook.Object
import GraphQLBook.Scalar
import GraphQLBook.ScalarCodecs
import GraphQLBook.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


height : SelectionSet Int GraphQLBook.Object.Page
height =
    Object.selectionForField "Int" "height" [] Decode.int


id : SelectionSet GraphQLBook.ScalarCodecs.Id GraphQLBook.Object.Page
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder)


image : SelectionSet String GraphQLBook.Object.Page
image =
    Object.selectionForField "String" "image" [] Decode.string


imageType : SelectionSet String GraphQLBook.Object.Page
imageType =
    Object.selectionForField "String" "imageType" [] Decode.string


pageNumber : SelectionSet Int GraphQLBook.Object.Page
pageNumber =
    Object.selectionForField "Int" "pageNumber" [] Decode.int


width : SelectionSet Int GraphQLBook.Object.Page
width =
    Object.selectionForField "Int" "width" [] Decode.int
