-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object.Position exposing (..)

import GraphQLBook.InputObject
import GraphQLBook.Interface
import GraphQLBook.Object
import GraphQLBook.Scalar
import GraphQLBook.ScalarCodecs
import GraphQLBook.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


group : SelectionSet Int GraphQLBook.Object.Position
group =
    Object.selectionForField "Int" "group" [] Decode.int


id : SelectionSet (Maybe GraphQLBook.ScalarCodecs.Id) GraphQLBook.Object.Position
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


x : SelectionSet Int GraphQLBook.Object.Position
x =
    Object.selectionForField "Int" "x" [] Decode.int


y : SelectionSet Int GraphQLBook.Object.Position
y =
    Object.selectionForField "Int" "y" [] Decode.int
