-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object.Translation exposing (..)

import GraphQLBook.InputObject
import GraphQLBook.Interface
import GraphQLBook.Object
import GraphQLBook.Scalar
import GraphQLBook.ScalarCodecs
import GraphQLBook.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


bookId : SelectionSet GraphQLBook.ScalarCodecs.Id GraphQLBook.Object.Translation
bookId =
    Object.selectionForField "ScalarCodecs.Id" "bookId" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder)


id : SelectionSet GraphQLBook.ScalarCodecs.Id GraphQLBook.Object.Translation
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder)


pageId : SelectionSet GraphQLBook.ScalarCodecs.Id GraphQLBook.Object.Translation
pageId =
    Object.selectionForField "ScalarCodecs.Id" "pageId" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder)


positions :
    SelectionSet decodesTo GraphQLBook.Object.Position
    -> SelectionSet (List decodesTo) GraphQLBook.Object.Translation
positions object_ =
    Object.selectionForCompositeField "positions" [] object_ (identity >> Decode.list)


text : SelectionSet String GraphQLBook.Object.Translation
text =
    Object.selectionForField "String" "text" [] Decode.string
