-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object.TranslationBook exposing (..)

import GraphQLBook.InputObject
import GraphQLBook.Interface
import GraphQLBook.Object
import GraphQLBook.Scalar
import GraphQLBook.ScalarCodecs
import GraphQLBook.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


author : SelectionSet String GraphQLBook.Object.TranslationBook
author =
    Object.selectionForField "String" "author" [] Decode.string


book :
    SelectionSet decodesTo GraphQLBook.Object.Book
    -> SelectionSet decodesTo GraphQLBook.Object.TranslationBook
book object_ =
    Object.selectionForCompositeField "book" [] object_ identity


id : SelectionSet GraphQLBook.ScalarCodecs.Id GraphQLBook.Object.TranslationBook
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GraphQLBook.ScalarCodecs.codecs |> GraphQLBook.Scalar.unwrapCodecs |> .codecId |> .decoder)


language :
    SelectionSet decodesTo GraphQLBook.Object.Language
    -> SelectionSet decodesTo GraphQLBook.Object.TranslationBook
language object_ =
    Object.selectionForCompositeField "language" [] object_ identity


notes : SelectionSet String GraphQLBook.Object.TranslationBook
notes =
    Object.selectionForField "String" "notes" [] Decode.string


pageTranslations :
    SelectionSet decodesTo GraphQLBook.Object.TranslationPage
    -> SelectionSet (List decodesTo) GraphQLBook.Object.TranslationBook
pageTranslations object_ =
    Object.selectionForCompositeField "pageTranslations" [] object_ (identity >> Decode.list)


title : SelectionSet String GraphQLBook.Object.TranslationBook
title =
    Object.selectionForField "String" "title" [] Decode.string


translations :
    SelectionSet decodesTo GraphQLBook.Object.Translation
    -> SelectionSet (List decodesTo) GraphQLBook.Object.TranslationBook
translations object_ =
    Object.selectionForCompositeField "translations" [] object_ (identity >> Decode.list)


translator : SelectionSet String GraphQLBook.Object.TranslationBook
translator =
    Object.selectionForField "String" "translator" [] Decode.string
