-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object exposing (..)


type Book
    = Book


type Category
    = Category


type Language
    = Language


type Page
    = Page


type Translation
    = Translation


type TranslationBook
    = TranslationBook


type TranslationPage
    = TranslationPage
