-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.Object exposing (..)


type Book
    = Book


type Page
    = Page


type Translation
    = Translation
