-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLBook.ScalarCodecs exposing (..)

import GraphQLBook.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    GraphQLBook.Scalar.Id


codecs : GraphQLBook.Scalar.Codecs Id
codecs =
    GraphQLBook.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
